### ISSUE TITLE
Extend max comment length

### ISSUE THREAD

**Issue by badtuple** [epilys/sic#15]
Right now it looks like comments are limited to 500 characters in length. Some restriction is good for the database and making sure users don't write their novel inline. But I ran into the 500 character limit super quickly when trying to reply to a post.

It looks like in the Lobsters rails schema the db field used is a MySQL medium text which would mean there's a limit of 16,777,215 bytes. A 16+ megabyte comment is pretty excessive. I looked through the code and couldn't find any other restrictions on it, though it wouldn't surprise me if I missed something.

If left up to me I'd make the limit 2,000 characters (or really 2,048 because I'm a nerd), since I'd want to encourage more indepth discussion. But figured I'd raise this issue here for discussion. There might be downsides to inlining values that large into sqlite but probably not for a while?

**Comment by epilys** [comment]
You're right that the limit is more of a problem than a solution. I think I will just remove it completely; if in the future it proves a problem (and I suspect it won't) it will be an easy change since the restriction is on the HTML side of things, not the database or business logic.
